(20 points)  Given the following variables:

name = 'Monty Python'

acct = 42

open_date = '10/12/2015'

balance = 2213.7

Use string methods or slices and format specifiers to align and format the values similar to the following (note the spacing and formatting):

First Name:		Monty    

Last Name:		Python

Account Number:		000042

Date Opened:		10/12/2015

Balance: 		$2,213.70

In [23]:
name = 'Monty Python'
acct = 42
open_date = '10/12/2015'
balance = 2213.7

print(name.split()[0])
print(f"First Name:         {name.split()[0]}")
print(f"Last Name:          {name.split()[1]}")
print(f"Account Number:     {acct:0>6}")
print(f"Date Opened:        {open_date}")
print(f"Balance:            ${balance:,.2f}")

Monty
First Name:         Monty
Last Name:          Python
Account Number:     000042
Date Opened:        10/12/2015
Balance:            $2,213.70

(15 points) Using only list slices, del and assignment, change the following list from:

[1, 2, 3, 4, 5, 6, 7, 8]

To:

[2, 4, 6, 8, 10, 12]

In [39]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
lst[0:4] = lst[1:len(lst):2]
lst[4] = 10
lst[5] = 12
del lst[6]
del lst[6]
print(lst)

[2, 4, 6, 8, 10, 12]

(15 points) Using only append, extend, insert and remove methods, change the following list from:

[1, 2, 3, 4, 5, 6, 7, 8]

To:

[2, 4, 6, 8, 10, 12]

In [55]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
lst.remove(1)
lst.remove(3)
lst.remove(5)
lst.remove(7)
lst.extend([10,12])
print(lst)

[2, 4, 6, 8, 10, 12]

(15 points) Write a for loop that will multiply all the numbers of a list together. Assume all of the items in the list are numbers.

In [56]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
mul = 1
for l in lst:
  mul = mul*l

print(mul)

40320

(10 points) Write a while loop that will multiply all the numbers of a list together (same as above but using a while loop)

In [61]:
lst = [1, 2, 3, 4, 5, 6, 7, 8]
mul = 1
i = 0
while i < len(lst):
  mul *= lst[i]
  i+=1
print(mul)

40320

(15 points) Write code to search through a list of strings and count the number of strings that begin with a capital letter. For example, given a list:

In [65]:
mylist = ['Abc', 'aeio', 'Berkeley', 'San Francisco', 'online']
ctr = 0
for s in mylist:
  if s[0].isupper():
    ctr += 1

print(ctr)

False
3